import grpc
from concurrent import futures
import sys
import os
import asyncio
from typing import List

# These would be generated by grpc_tools.protoc
# e.g., python -m grpc_tools.protoc -I./proto --python_out=./proto --grpc_python_out=./proto ./proto/embedding.proto
try:
    import proto.embedding_pb2 as embedding_pb2
    import proto.embedding_pb2_grpc as embedding_pb2_grpc
except ImportError:
    print("Warning: gRPC proto files not found. Generate them before running.")

from dense_encoder import DenseEncoder
from splade_encoder import SPLADEv2Encoder

class EmbeddingServiceServicer(embedding_pb2_grpc.EmbeddingServiceServicer):
    def __init__(self):
        self.dense = DenseEncoder()
        self.sparse = SPLADEv2Encoder()

    async def EncodeDense(self, request, context):
        try:
            texts = list(request.texts)
            embeddings = await self.dense.encode(texts)
            
            response = embedding_pb2.EncodeDenseResponse(model_dim=embeddings.shape[1], latency_ms=0.0)
            for vec in embeddings:
                response.vectors.append(embedding_pb2.DenseVector(values=vec.tolist()))
            return response
        except Exception as e:
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            return embedding_pb2.EncodeDenseResponse()

    async def EncodeSparse(self, request, context):
        try:
            texts = list(request.texts)
            sparse_dicts = self.sparse.encode(texts)
            
            response = embedding_pb2.EncodeSparseResponse()
            for d in sparse_dicts:
                indices = list(d.keys())
                values = list(d.values())
                response.vectors.append(embedding_pb2.SparseVector(indices=indices, values=values))
            return response
        except Exception as e:
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            return embedding_pb2.EncodeSparseResponse()

    async def EncodeHybrid(self, request, context):
        try:
            texts = list(request.texts)
            response = embedding_pb2.EncodeHybridResponse()
            
            if request.include_dense:
                embeddings = await self.dense.encode(texts)
                for vec in embeddings:
                    response.dense_vectors.append(embedding_pb2.DenseVector(values=vec.tolist()))
                    
            if request.include_sparse:
                sparse_dicts = self.sparse.encode(texts)
                for d in sparse_dicts:
                    indices = list(d.keys())
                    values = list(d.values())
                    response.sparse_vectors.append(embedding_pb2.SparseVector(indices=indices, values=values))
                    
            return response
        except Exception as e:
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            return embedding_pb2.EncodeHybridResponse()

async def serve():
    server = grpc.aio.server()
    embedding_pb2_grpc.add_EmbeddingServiceServicer_to_server(EmbeddingServiceServicer(), server)
    server.add_insecure_port('[::]:50051')
    print("Starting Embedding gRPC server on port 50051...")
    await server.start()
    await server.wait_for_termination()

if __name__ == '__main__':
    asyncio.run(serve())
